name: Build with Jeongie AI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel python3-virtualenv git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android SDK licenses & install Build Tools
      run: |
        yes | sdkmanager --licenses || true
        mkdir -p ~/.android
        echo "### User Agreements" > ~/.android/repositories.cfg
        yes | buildozer android debug || true  # agar dia bikin folder .buildozer

        # Install AIDL manually if needed
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d latest
        rm tools.zip

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Jeongie-APK
        path: bin/*.apk
