name: Build Jeongie APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      CMDLINE_TOOLS: $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel python3-virtualenv git zip unzip openjdk-17-jdk wget
        pip install --upgrade pip
        pip install buildozer cython

    - name: Create SDK root folders
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

    - name: Download Android SDK Command Line Tools
      run: |
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip
        unzip cmdline.zip -d cmdline-tools-temp
        mkdir -p latest
        mv cmdline-tools-temp/cmdline-tools/* latest/
        echo "CMD Tools content:"
        ls -R $ANDROID_SDK_ROOT/cmdline-tools

    - name: Set PATH and verify sdkmanager
      run: |
        export PATH=$CMDLINE_TOOLS/bin:$PATH
        if ! command -v sdkmanager > /dev/null; then
          echo "sdkmanager NOT FOUND!"
          exit 2
        fi
        echo "sdkmanager found at $(which sdkmanager)"

    - name: Accept Licenses
      run: |
        export PATH=$CMDLINE_TOOLS/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

    - name: Install SDK Packages
      run: |
        export PATH=$CMDLINE_TOOLS/bin:$PATH
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Jeongie-APK
        path: bin/*.apk
